
services:
  client:
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
      - ./client/.env.local
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/app/
    ports:
      - "3000:3000"


  server:
    platform: linux/arm64
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

volumes:
  postgres_data: